global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoPaginateTester.DataContracts;
global using UnoPaginateTester.DataContracts.Serialization;
global using UnoPaginateTester.Models;
global using UnoPaginateTester.Presentation;
global using UnoPaginateTester.Services.Caching;
global using UnoPaginateTester.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
